version: "2"

services:
######################################################### Sign-in #
  sonar-runner:
    container_name: sonar-scanner
    restart: always
    build:
      context: .
#      dockerfile: openshift.dockerfile
