appName: prime
licensePlate: 9c33a9
environment: dev
imageTag: dev
servletContextPath: /actuator/prometheus
urlStub: pharmanetenrolment.gov.bc.ca

frontend:
  cpuRequests: 50m
  memoryRequests: 50Mi
  replicaCount: 1

backend:
  cpuRequests: 50m
  memoryRequests: 50Mi
  replicaCount: 1

settings:
  environmentName: dev
  keycloak:
    url: https://common-logon-dev.hlth.gov.bc.ca/auth
    realm: "moh_applications"
    clientId: "PRIME-APPLICATION-LOCAL"